<<<<<<< HEAD
access_key_id: AKIAJ4QSOS5P7ZIIIL3Q
=======
access_key_id: AKIAJ4QSOS5P7ZIIIL3Q
>>>>>>> a1a21b67793ea5c220162c3159b73dd9ccf2f233
secret_access_key: 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